CREATE OR REPLACE PACKAGE consultaCentros
IS
TYPE TC IS REF CURSOR;

CREATE OR REPLACE PROCEDURE CONSULTACENTRONUMERO(PID IN NUMBER, CCENTROS OUT TC);
CREATE OR REPLACE PROCEDURE CONSULTACENTRONOMBRE(NOMBRE VARCHAR2, CCENTROS OUT TC);


END consultaCentros;

CREATE OR REPLACE PACKAGE BODY consultaCentros


PROCEDURE CONSULTACENTRONUMERO(PID IN NUMBER, CCENTROS OUT TC)
(
t_cursor OUT TC
)
IS
BEGIN
OPEN t_cursor FOR
	SELECT CENTRO_NO, NOMBRE, PROVINCIA, CIUDAD, CP, CALLE, TELEFONO 
	FROM CENTROS
	WHERE CENTRO_NO=PCENTRO_NO;
EXCEPTION
WHEN DATA_NOT_FOUND THEN
RAISE_APPLICATION_ERROR(-20012, "No hay centros dados de alta con ese numero de centro");
END CONSULTACENTRONUMERO;

PROCEDURE CONSULTACENTRONOMBRE(NOMBRE VARCHAR2, CCENTROS OUT TC)
(
t_cursor OUT TC
)
IS
BEGIN
OPEN t_cursor FOR
	SELECT CENTRO_NO, NOMBRE, PROVINCIA, CIUDAD, CP, CALLE, TELEFONO 
	FROM CENTROS
	WHERE CENTRO_NO=PCENTRO_NO;
EXCEPTION
WHEN DATA_NOT_FOUND THEN
RAISE_APPLICATION_ERROR(-2003, "No hay centros dados de alta con ese nombre de centro");
END CONSULTACENTRONOMBRE;


END consultaCentros;